[package]
name = "remoc-obs"
version = "0.1.0"
edition = "2021"
authors = ["Sebastian Urban <surban@surban.net>"]
readme = "README.md"
repository = "https://github.com/surban/remoc-obs/"
documentation = "https://docs.rs/remoc-obs"
rust-version = "1.57"
description = "Remotely observable collections for use with Remoc."
keywords = ["remote", "collections", "remoc"]
categories = ["asynchronous", "network-programming"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remoc = { version = "0.9.10", path = "../remoc/remoc", default-features = false, features = [
    "rch",
] }
tokio = { version = "1.0", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"

[dev-dependencies]
remoc = { version = "0.9.10", path = "../remoc/remoc", default-features = false, features = [
    "default-codec-json",
] }
