[package]
name = "remoc"
version = "0.8.0-pre3"
authors = ["Sebastian Urban <surban@surban.net>", "ENQT GmbH <su@enqt.de>"]
readme = "README.md"
repository = "https://github.com/ENQT-GmbH/remoc/"
edition = "2018"
description = "Remote multiplexed objects and channels"
keywords = ["remote", "channel", "rpc", "stream", "multiplexer"]
categories = ["asynchronous", "network-programming"]
license = "Apache-2.0"

[features]
default = ["full", "default-codec-json"]
full = [
    "serde",
    "rch",
    "rfn",
    "robj",
    "rtc",
    "default-codec-json",
    "codec-bincode",
    "codec-cbor",
    "codec-json",
    "codec-message-pack",
]
rch = ["serde"]
rfn = ["rch"]
robj = ["rch"]
rtc = ["rch", "remoc_macro", "async-trait"]

# Codecs
codec-bincode = ["bincode"]
default-codec-bincode = ["codec-bincode"]
codec-cbor = ["serde_cbor"]
default-codec-cbor = ["codec-cbor"]
codec-json = ["serde_json"]
default-codec-json = ["codec-json"]
codec-message-pack = ["rmp-serde"]
default-codec-message-pack = ["codec-message-pack"]

[dependencies]
remoc_macro = { version = "=0.8.0-pre3", path = "../remoc_macro", optional = true }

futures = "0.3"
tokio = { version = "1.11", features = ["macros", "rt", "sync", "time"] }
tokio-util = { version = "0.6", features = ["codec"] }
rand = "0.8"
log = "0.4"
bytes = "1"
byteorder = "1.4"
lazy_static = "1.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
async-trait = { version = "0.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

# Codecs
serde_json = { version = "1.0", optional = true }
bincode = { version = "1.3", optional = true }
serde_cbor = { version = "0.11", optional = true }
rmp-serde = { version = "0.15", optional = true }


[dev-dependencies]
tokio = { version = "1.11", features = [
    "net",
    "io-util",
    "rt",
    "rt-multi-thread",
] }
env_logger = "0.9"


[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
