[target.wasm32-unknown-unknown]
runner = "cargo run --release --quiet --manifest-path /data/surban/dev/rust-wasi-web/wasm-bindgen/crates/cli/Cargo.toml --bin wasm-bindgen-test-runner --"
#runner = "wasm-bindgen-test-runner"

[target.wasm32-wasip1]
runner = "cargo run --release --quiet --manifest-path /data/surban/dev/rust-wasi-web/wasm-bindgen/crates/cli/Cargo.toml --bin wasm-bindgen-test-runner --"
#runner = "wasmtime -S inherit-env"

[target.wasm32-wasip1-threads]
runner = "cargo run --release --quiet --manifest-path /data/surban/dev/rust-wasi-web/wasm-bindgen/crates/cli/Cargo.toml --bin wasm-bindgen-test-runner --"
#runner = "wasmtime -S threads -S inherit-env"
