[package]
name = "chmux"
version = "0.1.0"
authors = ["ENQT GmbH <su@enqt.de>"]
edition = "2018"
description = "Multiplexes multiple channels over a single channel (or anything that implements Sink and Stream)."
keywords = ["multiplex", "channel", "mux", "multiple", "channels"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
pin-project = "0.4"
rand = "0.7"

[dev-dependencies]
futures = { version="0.3", features = ["thread-pool"] }
