name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check version dependencies
        run: ./check_version.sh
      - name: Check code formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build
      - name: Build documentation
        run: cargo doc --no-deps --quiet
      - name: Run tests
        run: cargo test --quiet
      - name: Code analysis
        run: cargo clippy --quiet
      - name: Test rch feature only with Bincode codec
        run: cargo test --no-default-features --quiet --features rch --features default-codec-bincode
      - name: Test rfn feature only with CBOR codec
        run: cargo test --no-default-features --quiet --features rfn --features default-codec-cbor
      - name: Test robj feature only with JSON codec
        run: cargo test --no-default-features --quiet --features robj --features default-codec-json
      - name: Test rtc feature only with MessagePack codec
        run: cargo test --no-default-features --quiet --features rtc --features default-codec-message-pack
      - name: Install Cargo Tarpaulin for code coverate
        run: cargo install cargo-tarpaulin --locked --quiet
      - name: Code coverage
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cargo tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash)
