name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check version dependencies
        run: ./check_version.sh
      - name: Check code formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build
      - name: Build documentation
        run: cargo doc --no-deps --quiet
      - name: Code analysis
        run: cargo clippy --quiet
      - name: Run tests with JSON (default) codec
        run: cargo test --quiet
      - name: Run tests with Bincode codec
        run: cargo test --no-default-features --quiet --features full --features default-codec-bincode
      - name: Run tests with CBOR (serde_cbor) codec
        run: RUSTFLAGS="-A deprecated" cargo test --no-default-features --quiet --features full --features default-codec-cbor
      - name: Run tests with CBOR (ciborium) codec
        run: cargo test --no-default-features --quiet --features full --features default-codec-ciborium
      - name: Run tests with MessagePack codec
        run: cargo test --no-default-features --quiet --features full --features default-codec-message-pack
      - name: Test rch feature only
        run: cargo test --no-default-features --quiet --features rch --features default-codec-json
      - name: Test rfn feature only
        run: cargo test --no-default-features --quiet --features rfn --features default-codec-json
      - name: Test robj feature only
        run: cargo test --no-default-features --quiet --features robj --features default-codec-json
      - name: Test rtc feature only
        run: cargo test --no-default-features --quiet --features rtc --features default-codec-json
      - name: Build examples
        run: |
          cargo build --quiet --manifest-path examples/rtc/counter-client/Cargo.toml
          cargo build --quiet --manifest-path examples/rtc/counter-server/Cargo.toml
      - name: Test with MSRV 1.51
        run: |
          rustup install 1.51
          cargo +1.51 test --quiet
      - name: Install Cargo Tarpaulin for code coverage
        run: cargo install cargo-tarpaulin --locked --quiet
        continue-on-error: true
      - name: Code coverage
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cargo tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash)
        continue-on-error: true
