[package]
name = "chrpc_macro"
<<<<<<< HEAD
version = "0.1.0"
authors = ["ENQT GmbH <su@enqt.de>"]
=======
version = "0.2.0"
authors = ["Sebastian Urban <surban@surban.net>"]
>>>>>>> e047c6f... Identity codec
edition = "2018"
description = "Procedural macro for chrpc. Do not use directly."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full", "visit"] }
quote = "1.0"

[lib]
proc-macro = true
